In [2]:
from sklearn import tree
import pandas as pd

# 데이터 생성
golf_df = pd.DataFrame()

# 데이터 입력
# 날씨에 따라 골프를 쳤는지 안쳤는지 여부
golf_df['outlook'] = ['sunny', 'sunny', 'overcast', 'rainy', 'rainy', 'rainy',
                      'overcast', 'sunny', 'sunny', 'rainy', 'sunny', 'overcast',
                      'overcast', 'rainy']
golf_df['temperature'] = ['hot', 'hot', 'hot', 'mild', 'cool', 'cool', 'cool',
                          'mild', 'cool', 'mild', 'mild', 'mild', 'hot', 'mild']
golf_df['humidity'] = ['high', 'high', 'high', 'high', 'normal', 'normal',
                       'normal', 'high', 'normal', 'normal', 'normal', 'high',
                       'normal', 'high']
golf_df['windy'] = ['false', 'true', 'false', 'false', 'false', 'true',
                    'true', 'false', 'false', 'false', 'true', 'true',
                    'false', 'true']
golf_df['play'] = ['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no',
                   'yes', 'yes', 'yes', 'yes', 'yes', 'no']

golf_df

     outlook temperature humidity  windy play
0      sunny         hot     high  false   no
1      sunny         hot     high   true   no
2   overcast         hot     high  false  yes
3      rainy        mild     high  false  yes
4      rainy        cool   normal  false  yes
5      rainy        cool   normal   true   no
6   overcast        cool   normal   true  yes
7      sunny        mild     high  false   no
8      sunny        cool   normal  false  yes
9      rainy        mild   normal  false  yes
10     sunny        mild   normal   true  yes
11  overcast        mild     high   true  yes
12  overcast         hot   normal  false  yes
13     rainy        mild     high   true   no

In [3]:
# 데이터 전처리
# 글자로 된 데이터를 숫자로 변환
one_hot_data = pd.get_dummies(golf_df[['outlook', 'temperature', 'humidity', 'windy']])
one_hot_data

,outlook_overcast,outlook_rainy,outlook_sunny,temperature_cool,temperature_hot,temperature_mild,humidity_high,humidity_normal,windy_false,windy_true
0,0,0,1,0,1,0,1,0,1,0
1,0,0,1,0,1,0,1,0,0,1
2,1,0,0,0,1,0,1,0,1,0
3,0,1,0,0,0,1,1,0,1,0
4,0,1,0,1,0,0,0,1,1,0
5,0,1,0,1,0,0,0,1,0,1
6,1,0,0,1,0,0,0,1,0,1
7,0,0,1,0,0,1,1,0,1,0
8,0,0,1,1,0,0,0,1,1,0
9,0,1,0,0,0,1,0,1,1,0
10,0,0,1,0,0,1,0,1,0,1
11,1,0,0,0,0,1,1,0,0,1
12,1,0,0,0,1,0,0,1,1,0
13,0,1,0,0,0,1,1,0,0,1

In [4]:
# Decision tree classifier 생성
clf = tree.DecisionTreeClassifier()
# Decision tree 학습시키기
# 첫번째 인자는 학습데이터, 두번째 인자는 목표변수
clf_train = clf.fit(one_hot_data, golf_df['play'])


# 예측하기
# Outlook = sunny, Temp = hot, Humid = normal, Windy = false
prediction = clf_train.predict([[0, 0, 1, 0, 1, 0, 0, 1, 1, 0]])
prediction

/home/vietman2/.local/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['yes'], dtype=object)

In [7]:
# 평가하기

# Accuracy
from sklearn.metrics import accuracy_score
accuracy_score(golf_df['play'], clf_train.predict(one_hot_data))

# Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(golf_df['play'], clf_train.predict(one_hot_data))

# Precision
from sklearn.metrics import precision_score
precision_score(golf_df['play'], clf_train.predict(one_hot_data), average=None)

# Recall
from sklearn.metrics import recall_score
recall_score(golf_df['play'], clf_train.predict(one_hot_data), average=None)

# F1 Score
from sklearn.metrics import f1_score
f1_score(golf_df['play'], clf_train.predict(one_hot_data), average=None)

# print all metrics
print('Accuracy:', accuracy_score(golf_df['play'], clf_train.predict(one_hot_data)))
print('Precision:', precision_score(golf_df['play'], clf_train.predict(one_hot_data), average=None))
print('Recall:', recall_score(golf_df['play'], clf_train.predict(one_hot_data), average=None))

# Classification Report
from sklearn.metrics import classification_report
print(classification_report(golf_df['play'], clf_train.predict(one_hot_data)))

Accuracy: 1.0
Precision: [1. 1.]
Recall: [1. 1.]
              precision    recall  f1-score   support

          no       1.00      1.00      1.00         5
         yes       1.00      1.00      1.00         9

    accuracy                           1.00        14
   macro avg       1.00      1.00      1.00        14
weighted avg       1.00      1.00      1.00        14